/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import AppPackage.AnimationClass;
import Modelo.Slide;
import Modelo.Hash;
import Modelo.SqlUsuarios;
import Modelo.Usuarios;
import java.awt.Desktop;
import java.net.URI;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Slide slide;
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        slide = new Slide();
    }
    public void openInternet(){
        try {
            Desktop.getDesktop().browse(URI.create("https://github.com/garitaD"));
        } catch (Exception e) {
            System.err.println("Error in Login funcion openInternet" +e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegisttro = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtUsuario1 = new javax.swing.JTextField();
        txtPasswordReg = new javax.swing.JPasswordField();
        txtConfPassword = new javax.swing.JPasswordField();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblINGRESAR = new javax.swing.JLabel();
        pnlInicio = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblCronograma = new javax.swing.JLabel();
        lblProgramado = new javax.swing.JLabel();
        lblNotas = new javax.swing.JLabel();
        lblDrive = new javax.swing.JLabel();
        lblSocios = new javax.swing.JLabel();
        lblMantenimiento = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pnlIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        lblMenu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblCalculadora = new javax.swing.JLabel();
        lblMusica = new javax.swing.JLabel();
        lblInternet = new javax.swing.JLabel();
        lblRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1050, 575));
        setMinimumSize(new java.awt.Dimension(1050, 575));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRegisttro.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegisttro.setPreferredSize(new java.awt.Dimension(720, 480));
        pnlRegisttro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 4, 87));
        jLabel21.setText("Registro_");
        pnlRegisttro.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 150, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(146, 149, 154));
        lblNombre.setText("Nombre:");
        pnlRegisttro.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(146, 149, 154));
        jLabel23.setText("Correo:");
        pnlRegisttro.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 90, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(146, 149, 154));
        jLabel24.setText("Confirmar:");
        pnlRegisttro.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 130, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(146, 149, 154));
        jLabel25.setText("Password:");
        pnlRegisttro.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 130, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(146, 149, 154));
        jLabel26.setText("Usuario:");
        pnlRegisttro.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 100, -1));

        txtUsuario1.setBackground(new java.awt.Color(204, 204, 204));
        txtUsuario1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 4, 87)));
        pnlRegisttro.add(txtUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 200, 40));

        txtPasswordReg.setBackground(new java.awt.Color(204, 204, 204));
        txtPasswordReg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 4, 87)));
        pnlRegisttro.add(txtPasswordReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 200, 40));

        txtConfPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtConfPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 4, 87)));
        pnlRegisttro.add(txtConfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 200, 40));

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 4, 87)));
        pnlRegisttro.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 200, 40));

        txtCorreo.setBackground(new java.awt.Color(204, 204, 204));
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 4, 87)));
        pnlRegisttro.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 200, 40));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlRegisttro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 20, 310));

        lblINGRESAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Next_page_64px.png"))); // NOI18N
        lblINGRESAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblINGRESARMouseClicked(evt);
            }
        });
        pnlRegisttro.add(lblINGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 70, 60));

        getContentPane().add(pnlRegisttro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -530, 750, 530));

        pnlInicio.setBackground(new java.awt.Color(255, 255, 255));
        pnlInicio.setForeground(new java.awt.Color(255, 255, 255));
        pnlInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(29, 158, 0));
        jLabel18.setText("Cronograma");
        pnlInicio.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(29, 158, 0));
        jLabel14.setText("Programado");
        pnlInicio.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(29, 158, 0));
        jLabel15.setText("Notas");
        pnlInicio.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(29, 158, 0));
        jLabel16.setText("Socios");
        pnlInicio.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(29, 158, 0));
        jLabel17.setText("Mantenimiento");
        pnlInicio.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(29, 158, 0));
        jLabel13.setText("Google Drive");
        pnlInicio.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        lblCronograma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCronograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Clock_96px.png"))); // NOI18N
        lblCronograma.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCronogramaMouseMoved(evt);
            }
        });
        lblCronograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCronogramaMouseExited(evt);
            }
        });
        pnlInicio.add(lblCronograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, 180));

        lblProgramado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProgramado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Today_96px.png"))); // NOI18N
        lblProgramado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblProgramadoMouseMoved(evt);
            }
        });
        lblProgramado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProgramadoMouseExited(evt);
            }
        });
        pnlInicio.add(lblProgramado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 190, 180));

        lblNotas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Idea_96px.png"))); // NOI18N
        lblNotas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblNotasMouseMoved(evt);
            }
        });
        lblNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNotasMouseExited(evt);
            }
        });
        pnlInicio.add(lblNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 190, 180));

        lblDrive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDrive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Google_Drive_96px.png"))); // NOI18N
        lblDrive.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDriveMouseMoved(evt);
            }
        });
        lblDrive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDriveMouseExited(evt);
            }
        });
        pnlInicio.add(lblDrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 190, 180));

        lblSocios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Handshake_96px.png"))); // NOI18N
        lblSocios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSociosMouseMoved(evt);
            }
        });
        lblSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSociosMouseExited(evt);
            }
        });
        pnlInicio.add(lblSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 190, 180));

        lblMantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Maintenance_96px.png"))); // NOI18N
        lblMantenimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMantenimientoMouseMoved(evt);
            }
        });
        lblMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMantenimientoMouseExited(evt);
            }
        });
        pnlInicio.add(lblMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 190, 180));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Buscar...");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 158, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        pnlInicio.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 180, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_32px.png"))); // NOI18N
        pnlInicio.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 30, 30));

        getContentPane().add(pnlInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 750, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Multiply_32px.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 30, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 30, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 750, 50));

        pnlIngreso.setBackground(new java.awt.Color(255, 255, 255));
        pnlIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pnlIngreso.setForeground(new java.awt.Color(255, 255, 255));
        pnlIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(5, 113, 248));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(5, 113, 248));
        jLabel1.setText("Password:");
        pnlIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 90, 30));

        jLabel3.setBackground(new java.awt.Color(5, 113, 248));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(5, 113, 248));
        jLabel3.setText("User:");
        pnlIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 50, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_User_96px_2.png"))); // NOI18N
        pnlIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 100, 90));

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("Ingrese usuario");
        txtUsuario.setBorder(null);
        pnlIngreso.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 200, 30));

        jSeparator1.setForeground(new java.awt.Color(45, 45, 45));
        pnlIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 240, 20));

        jSeparator2.setForeground(new java.awt.Color(45, 45, 45));
        pnlIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 240, 20));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("hhhhhhhhhhhhhhhhh");
        txtPassword.setBorder(null);
        pnlIngreso.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 200, 40));

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Menu_32px.png"))); // NOI18N
        lblMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });
        pnlIngreso.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_customer_32px_1.png"))); // NOI18N
        pnlIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Key_32px.png"))); // NOI18N
        pnlIngreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_OFF.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_ON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_ON.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_ON.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        pnlIngreso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        lblCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Calculator_32px.png"))); // NOI18N
        lblCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCalculadoraMouseClicked(evt);
            }
        });
        pnlIngreso.add(lblCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 120, 30, 30));

        lblMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Musical_Notes_32px.png"))); // NOI18N
        lblMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMusicaMouseClicked(evt);
            }
        });
        pnlIngreso.add(lblMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 170, 30, 30));

        lblInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Globe_32px.png"))); // NOI18N
        lblInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInternetMouseClicked(evt);
            }
        });
        pnlIngreso.add(lblInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 70, 30, 30));

        lblRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRegistro.setForeground(new java.awt.Color(29, 158, 0));
        lblRegistro.setText("Registro");
        lblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistroMouseClicked(evt);
            }
        });
        pnlIngreso.add(lblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, -1, -1));

        getContentPane().add(pnlIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 310, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        // TODO add your handling code here:
        AnimationClass internet = new AnimationClass();
        internet.jLabelXRight(-40, 10, 10, 5, lblInternet);
        
        AnimationClass internett = new AnimationClass();
        internett.jLabelXLeft(10, -40, 10, 5, lblInternet);
        
        AnimationClass calculadora = new AnimationClass();
        internet.jLabelXRight(-40, 10, 10, 5, lblCalculadora);
        
        AnimationClass calculadoraa = new AnimationClass();
        internett.jLabelXLeft(10, -40, 10, 5, lblCalculadora);
        
        AnimationClass musica = new AnimationClass();
        internet.jLabelXRight(-40, 10, 10, 5, lblMusica);
        
        AnimationClass musicaa = new AnimationClass();
        internett.jLabelXLeft(10, -40, 10, 5, lblMusica);
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblCalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalculadoraMouseClicked
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            p.waitFor();
        } catch (Exception e) {
            System.err.println("Error in Login metodo lblCalculadora" +e);
        }
    }//GEN-LAST:event_lblCalculadoraMouseClicked

    private void lblMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMusicaMouseClicked
        
    }//GEN-LAST:event_lblMusicaMouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea salir del Login?","Exit", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void lblINGRESARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblINGRESARMouseClicked
        // TODO add your handling code here:
        SqlUsuarios modSql = new SqlUsuarios();
        Usuarios mod = new Usuarios();

        //Se traen los campos a evaluar
        String pass = new String(txtPasswordReg.getPassword());
        String passCon = new String(txtConfPassword.getPassword());

        if (txtUsuario.getText().equals("") || pass.equals("") || passCon.equals("")
                || txtNombre.getText().equals("") || txtCorreo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios, debe llenar todos los campos");

        } else {

            if (pass.equals(passCon)) {

                if (modSql.existeUsuario(txtUsuario.getText()) == 0) {

                    if (modSql.esEmail(txtCorreo.getText())) {
                        String nuevoPass = Hash.sha1(pass);

                        //Se envian los datos al modelo
                        mod.setUsuario(txtUsuario.getText());
                        mod.setPassword(nuevoPass);
                        mod.setNombre(txtNombre.getText());
                        mod.setCorreo(txtCorreo.getText());
                        mod.setId_tipo(1);//1 adm, 2 user normal

                        if (modSql.registrar(mod)) {

                            JOptionPane.showMessageDialog(null, "Registro Guardado");
                            limpiar();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al guardar");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El correo electronico no es valido");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ya existe");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }
        }
    }//GEN-LAST:event_lblINGRESARMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        SqlUsuarios modSql = new SqlUsuarios();
        Usuarios mod = new Usuarios();
        
        Date date = new Date();
        DateFormat fechaHora = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        
        String pass = new String(txtPassword.getPassword());
        
        if (!txtUsuario.getText().equals("") && !pass.equals("")){
            
            String nuevoPass = Hash.sha1(pass);
            mod.setUsuario(txtUsuario.getText());
            mod.setPassword(nuevoPass);
            mod.setLast_session(fechaHora.format(date));
            
            if (modSql.login(mod)) {
                
                this.dispose();
                
                Inicio frmInicio = new Inicio();
                frmInicio.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Datos Incorrectos");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe ingresar sus datos");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void lblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseClicked
        // TODO add your handling code here:
        slide.jPanelYAbajo(-530, 50, 10, 5, pnlRegisttro);
        slide.jPanelYArriba(50, -530, 10, 5, pnlRegisttro);
        
        slide.jPanelYArriba(50, -530, 10, 5, pnlInicio);
        slide.jPanelYAbajo(-530, 50, 10, 5, pnlInicio);
                                                
    }//GEN-LAST:event_lblRegistroMouseClicked

    private void lblCronogramaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCronogramaMouseMoved
        lblCronograma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
    }//GEN-LAST:event_lblCronogramaMouseMoved

    private void lblCronogramaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCronogramaMouseExited
        lblCronograma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblCronogramaMouseExited

    private void lblProgramadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProgramadoMouseMoved
        lblProgramado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblProgramadoMouseMoved

    private void lblProgramadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProgramadoMouseExited
        lblProgramado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblProgramadoMouseExited

    private void lblNotasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotasMouseMoved
        lblNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblNotasMouseMoved

    private void lblNotasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotasMouseExited
        lblNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblNotasMouseExited

    private void lblDriveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDriveMouseMoved
        lblDrive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblDriveMouseMoved

    private void lblDriveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDriveMouseExited
        lblDrive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblDriveMouseExited

    private void lblSociosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSociosMouseMoved
        lblSocios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblSociosMouseMoved

    private void lblSociosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSociosMouseExited
        lblSocios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblSociosMouseExited

    private void lblMantenimientoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimientoMouseMoved
        lblMantenimiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblMantenimientoMouseMoved

    private void lblMantenimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimientoMouseExited
        lblMantenimiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblMantenimientoMouseExited

    private void lblInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInternetMouseClicked
        openInternet();
    }//GEN-LAST:event_lblInternetMouseClicked
    private void limpiar() {
        txtUsuario.setText("");
        txtPasswordReg.setText("");
        txtConfPassword.setText("");
        txtNombre.setText("");
        txtCorreo.setText("");

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCalculadora;
    private javax.swing.JLabel lblCronograma;
    private javax.swing.JLabel lblDrive;
    private javax.swing.JLabel lblINGRESAR;
    private javax.swing.JLabel lblInternet;
    private javax.swing.JLabel lblMantenimiento;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMusica;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNotas;
    private javax.swing.JLabel lblProgramado;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblSocios;
    private javax.swing.JPanel pnlIngreso;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlRegisttro;
    private javax.swing.JPasswordField txtConfPassword;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordReg;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables
}
